/* tslint:disable */
/* eslint-disable */
/**
 * Recipe Maps API
 * Egyszerű API régiók és települések listázására.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * Kategória azonosítója
     * @type {number}
     * @memberof Category
     */
    'id': number;
    /**
     * Kategória neve
     * @type {string}
     * @memberof Category
     */
    'name'?: string | null;
}
/**
 * 
 * @export
 * @interface Geometry
 */
export interface Geometry {
    /**
     * 
     * @type {string}
     * @memberof Geometry
     */
    'type': GeometryTypeEnum;
    /**
     * 
     * @type {GeometryCoordinates}
     * @memberof Geometry
     */
    'coordinates': GeometryCoordinates;
}

export const GeometryTypeEnum = {
    Point: 'Point',
    LineString: 'LineString',
    Polygon: 'Polygon',
    MultiPoint: 'MultiPoint',
    MultiLineString: 'MultiLineString',
    MultiPolygon: 'MultiPolygon'
} as const;

export type GeometryTypeEnum = typeof GeometryTypeEnum[keyof typeof GeometryTypeEnum];

/**
 * @type GeometryCoordinates
 * GeoJSON koordináták
 * @export
 */
export type GeometryCoordinates = Array<Array<Array<number>>> | Array<Array<number>> | Array<number>;

/**
 * 
 * @export
 * @interface RecipeListItem
 */
export interface RecipeListItem {
    /**
     * 
     * @type {string}
     * @memberof RecipeListItem
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeListItem
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof RecipeListItem
     */
    'year'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeListItem
     */
    'settlement_id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeListItem
     */
    'category_id'?: number | null;
    /**
     * A recept hozz��val��i egy normaliz��lt sz��veges mez��ben.
     * @type {string}
     * @memberof RecipeListItem
     */
    'ingredients_text'?: string;
}
/**
 * 
 * @export
 * @interface RecipeListResponse
 */
export interface RecipeListResponse {
    /**
     * 
     * @type {number}
     * @memberof RecipeListResponse
     */
    'count': number;
    /**
     * 
     * @type {Array<RecipeListItem>}
     * @memberof RecipeListResponse
     */
    'items': Array<RecipeListItem>;
}
/**
 * 
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * Régió azonosítója
     * @type {number}
     * @memberof Region
     */
    'id': number;
    /**
     * Régió neve
     * @type {string}
     * @memberof Region
     */
    'name'?: string | null;
}
/**
 * 
 * @export
 * @interface RegionWithGeom
 */
export interface RegionWithGeom {
    /**
     * Régió azonosítója
     * @type {number}
     * @memberof RegionWithGeom
     */
    'id': number;
    /**
     * Régió neve
     * @type {string}
     * @memberof RegionWithGeom
     */
    'name'?: string | null;
    /**
     * 
     * @type {Geometry}
     * @memberof RegionWithGeom
     */
    'geom'?: Geometry;
}
/**
 * 
 * @export
 * @interface Settlement
 */
export interface Settlement {
    /**
     * Település azonosítója
     * @type {number}
     * @memberof Settlement
     */
    'id': number;
    /**
     * Település neve
     * @type {string}
     * @memberof Settlement
     */
    'name'?: string | null;
    /**
     * Régió azonosító
     * @type {number}
     * @memberof Settlement
     */
    'regionid'?: number | null;
}
/**
 * 
 * @export
 * @interface SettlementWithGeom
 */
export interface SettlementWithGeom {
    /**
     * Település azonosítója
     * @type {number}
     * @memberof SettlementWithGeom
     */
    'id': number;
    /**
     * Település neve
     * @type {string}
     * @memberof SettlementWithGeom
     */
    'name'?: string | null;
    /**
     * Régió azonosító
     * @type {number}
     * @memberof SettlementWithGeom
     */
    'regionid'?: number | null;
    /**
     * 
     * @type {Geometry}
     * @memberof SettlementWithGeom
     */
    'geom'?: Geometry;
}

/**
 * MapsApi - axios parameter creator
 * @export
 */
export const MapsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Visszaadja az összes régiót név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
         * @summary Régiók listázása (GeoJSON geometriával)
         * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMapsRegionsGet: async (regionId?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/maps/regions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (regionId) {
                localVarQueryParameter['regionId'] = regionId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Visszaadja az összes települést név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
         * @summary Települések listázása (GeoJSON geometriával)
         * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
         * @param {Array<number>} [settlementid] Opcionális szűrés. Több település ID is megadható (?settlementid&#x3D;101&amp;settlementid&#x3D;102) vagy vesszővel elválasztva (?settlementid&#x3D;101,102).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMapsSettlementsGet: async (regionId?: Array<number>, settlementid?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/maps/settlements`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (regionId) {
                localVarQueryParameter['regionId'] = regionId;
            }

            if (settlementid) {
                localVarQueryParameter['settlementid'] = settlementid;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MapsApi - functional programming interface
 * @export
 */
export const MapsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MapsApiAxiosParamCreator(configuration)
    return {
        /**
         * Visszaadja az összes régiót név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
         * @summary Régiók listázása (GeoJSON geometriával)
         * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMapsRegionsGet(regionId?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RegionWithGeom>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiMapsRegionsGet(regionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MapsApi.apiMapsRegionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Visszaadja az összes települést név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
         * @summary Települések listázása (GeoJSON geometriával)
         * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
         * @param {Array<number>} [settlementid] Opcionális szűrés. Több település ID is megadható (?settlementid&#x3D;101&amp;settlementid&#x3D;102) vagy vesszővel elválasztva (?settlementid&#x3D;101,102).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMapsSettlementsGet(regionId?: Array<number>, settlementid?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SettlementWithGeom>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiMapsSettlementsGet(regionId, settlementid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MapsApi.apiMapsSettlementsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MapsApi - factory interface
 * @export
 */
export const MapsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MapsApiFp(configuration)
    return {
        /**
         * Visszaadja az összes régiót név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
         * @summary Régiók listázása (GeoJSON geometriával)
         * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMapsRegionsGet(regionId?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<Array<RegionWithGeom>> {
            return localVarFp.apiMapsRegionsGet(regionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Visszaadja az összes települést név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
         * @summary Települések listázása (GeoJSON geometriával)
         * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
         * @param {Array<number>} [settlementid] Opcionális szűrés. Több település ID is megadható (?settlementid&#x3D;101&amp;settlementid&#x3D;102) vagy vesszővel elválasztva (?settlementid&#x3D;101,102).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMapsSettlementsGet(regionId?: Array<number>, settlementid?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<Array<SettlementWithGeom>> {
            return localVarFp.apiMapsSettlementsGet(regionId, settlementid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MapsApi - object-oriented interface
 * @export
 * @class MapsApi
 * @extends {BaseAPI}
 */
export class MapsApi extends BaseAPI {
    /**
     * Visszaadja az összes régiót név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
     * @summary Régiók listázása (GeoJSON geometriával)
     * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MapsApi
     */
    public apiMapsRegionsGet(regionId?: Array<number>, options?: RawAxiosRequestConfig) {
        return MapsApiFp(this.configuration).apiMapsRegionsGet(regionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Visszaadja az összes települést név szerinti rendezéssel. A `geom` mező GeoJSON Geometry objektum.
     * @summary Települések listázása (GeoJSON geometriával)
     * @param {Array<number>} [regionId] Opcionális szűrés. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2).
     * @param {Array<number>} [settlementid] Opcionális szűrés. Több település ID is megadható (?settlementid&#x3D;101&amp;settlementid&#x3D;102) vagy vesszővel elválasztva (?settlementid&#x3D;101,102).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MapsApi
     */
    public apiMapsSettlementsGet(regionId?: Array<number>, settlementid?: Array<number>, options?: RawAxiosRequestConfig) {
        return MapsApiFp(this.configuration).apiMapsSettlementsGet(regionId, settlementid, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RecipesApi - axios parameter creator
 * @export
 */
export const RecipesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Visszaadja az összes recept kategóriát név szerinti rendezéssel.
         * @summary Kategóriák listázása
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRecipesCategoriesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/recipes/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Visszaadja az összes receptet, opcionális szűrőkkel (év, település, kategória, régió). A válasz tartalmazza az összes találat számát is.
         * @summary Receptek listázása
         * @param {Array<number>} [regionId] Opcionális szűrés régió(k) szerint. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2). A régió szűrő település ID-kká kerül kibontásra.
         * @param {Array<number>} [year] 
         * @param {Array<number>} [settlementId] Opcionális szűrés település(ek) szerint.
         * @param {Array<number>} [categoryId] Opcionális szűrés kategória(k) szerint.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRecipesGet: async (regionId?: Array<number>, year?: Array<number>, settlementId?: Array<number>, categoryId?: Array<number>, ingredients?: Array<string>, reverse?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/recipes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (regionId) {
                localVarQueryParameter['regionId'] = regionId;
            }

            if (year) {
                localVarQueryParameter['year'] = year;
            }

            if (settlementId) {
                localVarQueryParameter['settlementId'] = settlementId;
            }

            if (categoryId) {
                localVarQueryParameter['categoryId'] = categoryId;
            }

            if (ingredients) {
                localVarQueryParameter['ingredients'] = ingredients;
            }

            if (reverse !== undefined) {
                localVarQueryParameter['reverse'] = reverse;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecipesApi - functional programming interface
 * @export
 */
export const RecipesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecipesApiAxiosParamCreator(configuration)
    return {
        /**
         * Visszaadja az összes recept kategóriát név szerinti rendezéssel.
         * @summary Kategóriák listázása
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRecipesCategoriesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Category>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiRecipesCategoriesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.apiRecipesCategoriesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Visszaadja az összes receptet, opcionális szűrőkkel (év, település, kategória, régió). A válasz tartalmazza az összes találat számát is.
         * @summary Receptek listázása
         * @param {Array<number>} [regionId] Opcionális szűrés régió(k) szerint. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2). A régió szűrő település ID-kká kerül kibontásra.
         * @param {Array<number>} [year] 
         * @param {Array<number>} [settlementId] Opcionális szűrés település(ek) szerint.
         * @param {Array<number>} [categoryId] Opcionális szűrés kategória(k) szerint.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRecipesGet(regionId?: Array<number>, year?: Array<number>, settlementId?: Array<number>, categoryId?: Array<number>, ingredients?: Array<string>, reverse?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipeListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiRecipesGet(regionId, year, settlementId, categoryId, ingredients, reverse, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.apiRecipesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecipesApi - factory interface
 * @export
 */
export const RecipesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecipesApiFp(configuration)
    return {
        /**
         * Visszaadja az összes recept kategóriát név szerinti rendezéssel.
         * @summary Kategóriák listázása
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRecipesCategoriesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Category>> {
            return localVarFp.apiRecipesCategoriesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Visszaadja az összes receptet, opcionális szűrőkkel (év, település, kategória, régió). A válasz tartalmazza az összes találat számát is.
         * @summary Receptek listázása
         * @param {Array<number>} [regionId] Opcionális szűrés régió(k) szerint. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2). A régió szűrő település ID-kká kerül kibontásra.
         * @param {Array<number>} [year] 
         * @param {Array<number>} [settlementId] Opcionális szűrés település(ek) szerint.
         * @param {Array<number>} [categoryId] Opcionális szűrés kategória(k) szerint.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRecipesGet(regionId?: Array<number>, year?: Array<number>, settlementId?: Array<number>, categoryId?: Array<number>, ingredients?: Array<string>, reverse?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<RecipeListResponse> {
            return localVarFp.apiRecipesGet(regionId, year, settlementId, categoryId, ingredients, reverse, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecipesApi - object-oriented interface
 * @export
 * @class RecipesApi
 * @extends {BaseAPI}
 */
export class RecipesApi extends BaseAPI {
    /**
     * Visszaadja az összes recept kategóriát név szerinti rendezéssel.
     * @summary Kategóriák listázása
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public apiRecipesCategoriesGet(options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).apiRecipesCategoriesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Visszaadja az összes receptet, opcionális szűrőkkel (év, település, kategória, régió). A válasz tartalmazza az összes találat számát is.
     * @summary Receptek listázása
     * @param {Array<number>} [regionId] Opcionális szűrés régió(k) szerint. Több regionId megadható (?regionId&#x3D;1&amp;regionId&#x3D;2) vagy vesszővel elválasztva (?regionId&#x3D;1,2). A régió szűrő település ID-kká kerül kibontásra.
     * @param {Array<number>} [year] 
     * @param {Array<number>} [settlementId] Opcionális szűrés település(ek) szerint.
     * @param {Array<number>} [categoryId] Opcionális szűrés kategória(k) szerint.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public apiRecipesGet(regionId?: Array<number>, year?: Array<number>, settlementId?: Array<number>, categoryId?: Array<number>, ingredients?: Array<string>, reverse?: boolean, options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).apiRecipesGet(regionId, year, settlementId, categoryId, ingredients, reverse, options).then((request) => request(this.axios, this.basePath));
    }
}
